config/routes.rb
Profiles::Application.routes.draw do

  resources :cost_centers

  resources :accounts

  resources :profile_units

  resources :matrix_units

end

app/models/profile_unit.rb
class ProfileUnit < ActiveRecord::Base
	belongs_to :matrix_units
	has_one :cost_center
	has_one :account
end

app/controllers/profile_units_controller.rb
class ProfileUnitsController < ApplicationController
  # GET /profile_units
  # GET /profile_units.json
  def index
    @profile_units = ProfileUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profile_units }
    end
  end

  # GET /profile_units/1
  # GET /profile_units/1.json
  def show
    @profile_unit = ProfileUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile_unit }
    end
  end

  # GET /profile_units/new
  # GET /profile_units/new.json
  def new
    @profile_unit = ProfileUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile_unit }
    end
  end

  # GET /profile_units/1/edit
  def edit
    @profile_unit = ProfileUnit.find(params[:id])
  end

  # POST /profile_units
  # POST /profile_units.json
  def create
    @profile_unit = ProfileUnit.new(params[:profile_unit])

    respond_to do |format|
      if @profile_unit.save
        format.html { redirect_to @profile_unit, notice: 'Profile unit was successfully created.' }
        format.json { render json: @profile_unit, status: :created, location: @profile_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @profile_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profile_units/1
  # PUT /profile_units/1.json
  def update
    @profile_unit = ProfileUnit.find(params[:id])

    respond_to do |format|
      if @profile_unit.update_attributes(params[:profile_unit])
        format.html { redirect_to @profile_unit, notice: 'Profile unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_units/1
  # DELETE /profile_units/1.json
  def destroy
    @profile_unit = ProfileUnit.find(params[:id])
    @profile_unit.destroy

    respond_to do |format|
      format.html { redirect_to profile_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profile_units_helper.rb
module ProfileUnitsHelper
end

app/views/profile_units/_form.html.erb
<%= form_for(@profile_unit) do |f| %>
  <% if @profile_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_unit.errors.count, "error") %> prohibited this profile_unit from being saved:</h2>

      <ul>
      <% @profile_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matrix_unit_id %><br />
    <%= f.number_field :matrix_unit_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.number_field :period %>
  </div>
  <div class="field">
    <%= f.label :profile_type %><br />
    <%= f.text_field :profile_type %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :cost_center_id %><br />
    <%= f.number_field :cost_center_id %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :fund %><br />
    <%= f.text_field :fund %>
  </div>
  <div class="field">
    <%= f.label :linked %><br />
    <%= f.check_box :linked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_units/edit.html.erb
<h1>Editing profile_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile_unit %> |
<%= link_to 'Back', profile_units_path %>

app/views/profile_units/index.html.erb
<h1>Listing profile_units</h1>

<table>
  <tr>
    <th>Matrix Unit</th>
    <th>Year</th>
    <th>Period</th>
    <th>Profile type</th>
    <th>Status</th>
    <th>Cost center</th>
    <th>Account</th>
    <th>Amount</th>
    <th>Fund</th>
    <th>Linked</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profile_units.each do |profile_unit| %>
  <tr>
    <td><%= profile_unit.matrix_unit_id %></td>
    <td><%= profile_unit.year %></td>
    <td><%= profile_unit.period %></td>
    <td><%= profile_unit.profile_type %></td>
    <td><%= profile_unit.status %></td>
    <td><%= profile_unit.cost_center_id %></td>
    <td><%= profile_unit.account_id %></td>
    <td><%= profile_unit.amount %></td>
    <td><%= profile_unit.fund %></td>
    <td><%= profile_unit.linked %></td>
    <td><%= link_to 'Show', profile_unit %></td>
    <td><%= link_to 'Edit', edit_profile_unit_path(profile_unit) %></td>
    <td><%= link_to 'Destroy', profile_unit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile unit', new_profile_unit_path %>

app/views/profile_units/new.html.erb
<h1>New profile_unit</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_units_path %>

app/views/profile_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matrix Unit:</b>
  <%= @profile_unit.matrix_unit_id %>
</p>

<p>
  <b>Year:</b>
  <%= @profile_unit.year %>
</p>

<p>
  <b>Period:</b>
  <%= @profile_unit.period %>
</p>

<p>
  <b>Profile type:</b>
  <%= @profile_unit.profile_type %>
</p>

<p>
  <b>Status:</b>
  <%= @profile_unit.status %>
</p>

<p>
  <b>Cost center:</b>
  <%= @profile_unit.cost_center_id %>
</p>

<p>
  <b>Account:</b>
  <%= @profile_unit.account_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @profile_unit.amount %>
</p>

<p>
  <b>Fund:</b>
  <%= @profile_unit.fund %>
</p>

<p>
  <b>Linked:</b>
  <%= @profile_unit.linked %>
</p>


<%= link_to 'Edit', edit_profile_unit_path(@profile_unit) %> |
<%= link_to 'Back', profile_units_path %>