config/routes.rb
Profiles::Application.routes.draw do

  resources :cost_centers

  resources :accounts

  resources :profile_units

  resources :matrix_units

end

app/models/cost_center.rb
class CostCenter < ActiveRecord::Base
	has_many :matrix_units
	has_many :profile_units
end

app/controllers/cost_centers_controller.rb
class CostCentersController < ApplicationController
  # GET /cost_centers
  # GET /cost_centers.json
  def index
    @cost_centers = CostCenter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cost_centers }
    end
  end

  # GET /cost_centers/1
  # GET /cost_centers/1.json
  def show
    @cost_center = CostCenter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cost_center }
    end
  end

  # GET /cost_centers/new
  # GET /cost_centers/new.json
  def new
    @cost_center = CostCenter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cost_center }
    end
  end

  # GET /cost_centers/1/edit
  def edit
    @cost_center = CostCenter.find(params[:id])
  end

  # POST /cost_centers
  # POST /cost_centers.json
  def create
    @cost_center = CostCenter.new(params[:cost_center])

    respond_to do |format|
      if @cost_center.save
        format.html { redirect_to @cost_center, notice: 'Cost center was successfully created.' }
        format.json { render json: @cost_center, status: :created, location: @cost_center }
      else
        format.html { render action: "new" }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cost_centers/1
  # PUT /cost_centers/1.json
  def update
    @cost_center = CostCenter.find(params[:id])

    respond_to do |format|
      if @cost_center.update_attributes(params[:cost_center])
        format.html { redirect_to @cost_center, notice: 'Cost center was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cost_center.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cost_centers/1
  # DELETE /cost_centers/1.json
  def destroy
    @cost_center = CostCenter.find(params[:id])
    @cost_center.destroy

    respond_to do |format|
      format.html { redirect_to cost_centers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cost_centers_helper.rb
module CostCentersHelper
end

app/views/cost_centers/_form.html.erb
<%= form_for(@cost_center) do |f| %>
  <% if @cost_center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost_center.errors.count, "error") %> prohibited this cost_center from being saved:</h2>

      <ul>
      <% @cost_center.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cost_center %><br />
    <%= f.text_field :cost_center %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cost_centers/edit.html.erb
<h1>Editing cost_center</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost_center %> |
<%= link_to 'Back', cost_centers_path %>

app/views/cost_centers/index.html.erb
<h1>Listing cost_centers</h1>

<table>
  <tr>
    <th>Cost center</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cost_centers.each do |cost_center| %>
  <tr>
    <td><%= cost_center.cost_center %></td>
    <td><%= cost_center.description %></td>
    <td><%= link_to 'Show', cost_center %></td>
    <td><%= link_to 'Edit', edit_cost_center_path(cost_center) %></td>
    <td><%= link_to 'Destroy', cost_center, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cost center', new_cost_center_path %>

app/views/cost_centers/new.html.erb
<h1>New cost_center</h1>

<%= render 'form' %>

<%= link_to 'Back', cost_centers_path %>

app/views/cost_centers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cost center:</b>
  <%= @cost_center.cost_center %>
</p>

<p>
  <b>Description:</b>
  <%= @cost_center.description %>
</p>


<%= link_to 'Edit', edit_cost_center_path(@cost_center) %> |
<%= link_to 'Back', cost_centers_path %>