config/routes.rb
Profiles::Application.routes.draw do

  resources :cost_centers

  resources :accounts

  resources :profile_units

  resources :matrix_units

end

app/models/matrix_unit.rb
class MatrixUnit < ActiveRecord::Base
	has_many :profile_units
	has_one :cost_center
	has_one :account
end

app/controllers/matrix_units_controller.rb
class MatrixUnitsController < ApplicationController
  # GET /matrix_units
  # GET /matrix_units.json
  def index
    @matrix_units = MatrixUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matrix_units }
    end
  end

  # GET /matrix_units/1
  # GET /matrix_units/1.json
  def show
    @matrix_unit = MatrixUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @matrix_unit }
    end
  end

  # GET /matrix_units/new
  # GET /matrix_units/new.json
  def new
    @matrix_unit = MatrixUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @matrix_unit }
    end
  end

  # GET /matrix_units/1/edit
  def edit
    @matrix_unit = MatrixUnit.find(params[:id])
    @cost_centers = CostCenter.all
  end

  # POST /matrix_units
  # POST /matrix_units.json
  def create
    @matrix_unit = MatrixUnit.new(params[:matrix_unit])

    respond_to do |format|
      if @matrix_unit.save
        format.html { redirect_to @matrix_unit, notice: 'Matrix unit was successfully created.' }
        format.json { render json: @matrix_unit, status: :created, location: @matrix_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @matrix_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matrix_units/1
  # PUT /matrix_units/1.json
  def update
    @matrix_unit = MatrixUnit.find(params[:id])
    @cost_centers = CostCenter.all

    respond_to do |format|
      if @matrix_unit.update_attributes(params[:matrix_unit])
        format.html { redirect_to @matrix_unit, notice: 'Matrix unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @matrix_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matrix_units/1
  # DELETE /matrix_units/1.json
  def destroy
    @matrix_unit = MatrixUnit.find(params[:id])
    @matrix_unit.destroy

    respond_to do |format|
      format.html { redirect_to matrix_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/matrix_units_helper.rb
module MatrixUnitsHelper
end

app/views/matrix_units/_form.html.erb
<%= form_for(@matrix_unit) do |f| %>
  <% if @matrix_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@matrix_unit.errors.count, "error") %> prohibited this matrix_unit from being saved:</h2>

      <ul>
      <% @matrix_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label :period %><br />
    <%= f.number_field :period %>
  </div>
  <div class="field">
    <%= f.label :profile_type %><br />
    <%= f.text_field :profile_type %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :cost_center_id %><br />
    <%= f.collection_select :cost_center_id, @cost_centers, :id, :cost_center %>
    <!--<%= f.number_field :cost_center_id %>-->
  </div>
  <div class="field">
    <%= f.label :account_id %><br />
    <%= f.number_field :account_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matrix_units/edit.html.erb
<h1>Editing matrix_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @matrix_unit %> |
<%= link_to 'Back', matrix_units_path %>

app/views/matrix_units/index.html.erb
<h1>Listing matrix_units</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Period</th>
    <th>Profile type</th>
    <th>Status</th>
    <th>Cost center</th>
    <th>Account</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matrix_units.each do |matrix_unit| %>
  <tr>
    <td><%= matrix_unit.year %></td>
    <td><%= matrix_unit.period %></td>
    <td><%= matrix_unit.profile_type %></td>
    <td><%= matrix_unit.status %></td>
    <td><%= matrix_unit.cost_center_id %></td>
    <td><%= matrix_unit.account_id %></td>
    <td><%= matrix_unit.amount %></td>
    <td><%= link_to 'Show', matrix_unit %></td>
    <td><%= link_to 'Edit', edit_matrix_unit_path(matrix_unit) %></td>
    <td><%= link_to 'Destroy', matrix_unit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Matrix unit', new_matrix_unit_path %>

app/views/matrix_units/new.html.erb
<h1>New matrix_unit</h1>

<%= render 'form' %>

<%= link_to 'Back', matrix_units_path %>

app/views/matrix_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @matrix_unit.year %>
</p>

<p>
  <b>Period:</b>
  <%= @matrix_unit.period %>
</p>

<p>
  <b>Profile type:</b>
  <%= @matrix_unit.profile_type %>
</p>

<p>
  <b>Status:</b>
  <%= @matrix_unit.status %>
</p>

<p>
  <b>Cost center:</b>
  <%= @matrix_unit.cost_center_id %>
</p>

<p>
  <b>Account:</b>
  <%= @matrix_unit.account_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @matrix_unit.amount %>
</p>


<%= link_to 'Edit', edit_matrix_unit_path(@matrix_unit) %> |
<%= link_to 'Back', matrix_units_path %>